### ISSUE TITLE
Similar projects

### ISSUE THREAD

**Issue by rugk** [ENT8R/datakick#3]
Remember there is stuff/are apps like https://world.openfoodfacts.org/, which have the same aim and already have a database and an app.

**Comment by ENT8R** [comment]
I know... I'm also aware of these databases and I actually use [openfoodfacts](https://world.openfoodfacts.org/) and their API to get the name of a product by its barcode for another project.
I'm also not affiliated with [datakick](https://www.datakick.org/) or any other database but datakick is only a pretty small database (I think it only has 5000 items), so I thought I could contribute to this project by writing a NodeJS module for it.
So do you want me to add some other projects like [datakick](https://www.datakick.org/) to the readme?

**Comment by rugk** [comment]
Ah, no, now I understand what this project is actually about. Sorry, …

**Comment by ENT8R** [comment]
No problem. Did you thought that this project would be the database and the website of datakick.org?

**Comment by rugk** [comment]
Yes, … websites backends are also often written in NodeJS and I only had a quick look at the GitHub page. :wink: 

At least many other API implementations named their project "datakick-android" or "datakick-ios" or so. Maybe that's a thing you can do. :smile:

**Comment by ENT8R** [comment]
> At least many other API implementations named their project "datakick-android" or "datakick-ios" or so

https://docs.npmjs.com/files/package.json#name says

> Don't put "js" or "node" in the name. It's assumed that it's js, since you're writing a package.json file

that's why I didn't put a "node" in front...

**Comment by rugk** [comment]
Hmm yeah… or maybe "API" or whatever…

**Comment by rugk** [comment]
Or just only call the GitHub repo as such.
